/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as TrainersTrainerIdRouteImport } from './routes/trainers.$trainerId'
import { Route as TrainerProfileRouteImport } from './routes/trainer.profile'
import { Route as TrainerClientsRouteImport } from './routes/trainer.clients'
import { Route as ClientWorkoutsRouteImport } from './routes/client.workouts'
import { Route as ClientProfileRouteImport } from './routes/client.profile'

const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const TrainersTrainerIdRoute = TrainersTrainerIdRouteImport.update({
  id: '/$trainerId',
  path: '/$trainerId',
  getParentRoute: () => TrainersRoute,
} as any)
const TrainerProfileRoute = TrainerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerClientsRoute = TrainerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => TrainerRoute,
} as any)
const ClientWorkoutsRoute = ClientWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/help-center': typeof HelpCenterRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/trainers': typeof TrainersRouteWithChildren
  '/client/profile': typeof ClientProfileRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/trainers/$trainerId': typeof TrainersTrainerIdRoute
  '/client/': typeof ClientIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/help-center': typeof HelpCenterRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trainers': typeof TrainersRouteWithChildren
  '/client/profile': typeof ClientProfileRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/trainers/$trainerId': typeof TrainersTrainerIdRoute
  '/client': typeof ClientIndexRoute
  '/trainer': typeof TrainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/help-center': typeof HelpCenterRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/trainers': typeof TrainersRouteWithChildren
  '/client/profile': typeof ClientProfileRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/trainers/$trainerId': typeof TrainersTrainerIdRoute
  '/client/': typeof ClientIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/client'
    | '/community'
    | '/contact'
    | '/help-center'
    | '/privacy'
    | '/terms'
    | '/trainer'
    | '/trainers'
    | '/client/profile'
    | '/client/workouts'
    | '/trainer/clients'
    | '/trainer/profile'
    | '/trainers/$trainerId'
    | '/client/'
    | '/trainer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/contact'
    | '/help-center'
    | '/privacy'
    | '/terms'
    | '/trainers'
    | '/client/profile'
    | '/client/workouts'
    | '/trainer/clients'
    | '/trainer/profile'
    | '/trainers/$trainerId'
    | '/client'
    | '/trainer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/client'
    | '/community'
    | '/contact'
    | '/help-center'
    | '/privacy'
    | '/terms'
    | '/trainer'
    | '/trainers'
    | '/client/profile'
    | '/client/workouts'
    | '/trainer/clients'
    | '/trainer/profile'
    | '/trainers/$trainerId'
    | '/client/'
    | '/trainer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClientRoute: typeof ClientRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  HelpCenterRoute: typeof HelpCenterRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrainerRoute: typeof TrainerRouteWithChildren
  TrainersRoute: typeof TrainersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/trainers/$trainerId': {
      id: '/trainers/$trainerId'
      path: '/$trainerId'
      fullPath: '/trainers/$trainerId'
      preLoaderRoute: typeof TrainersTrainerIdRouteImport
      parentRoute: typeof TrainersRoute
    }
    '/trainer/profile': {
      id: '/trainer/profile'
      path: '/profile'
      fullPath: '/trainer/profile'
      preLoaderRoute: typeof TrainerProfileRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/clients': {
      id: '/trainer/clients'
      path: '/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/client/workouts': {
      id: '/client/workouts'
      path: '/workouts'
      fullPath: '/client/workouts'
      preLoaderRoute: typeof ClientWorkoutsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientProfileRoute: typeof ClientProfileRoute
  ClientWorkoutsRoute: typeof ClientWorkoutsRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientProfileRoute: ClientProfileRoute,
  ClientWorkoutsRoute: ClientWorkoutsRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface TrainerRouteChildren {
  TrainerClientsRoute: typeof TrainerClientsRoute
  TrainerProfileRoute: typeof TrainerProfileRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerClientsRoute: TrainerClientsRoute,
  TrainerProfileRoute: TrainerProfileRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

interface TrainersRouteChildren {
  TrainersTrainerIdRoute: typeof TrainersTrainerIdRoute
}

const TrainersRouteChildren: TrainersRouteChildren = {
  TrainersTrainerIdRoute: TrainersTrainerIdRoute,
}

const TrainersRouteWithChildren = TrainersRoute._addFileChildren(
  TrainersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClientRoute: ClientRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  HelpCenterRoute: HelpCenterRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrainerRoute: TrainerRouteWithChildren,
  TrainersRoute: TrainersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
